version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    environment:
       MYSQL_DATABASE: wordpress
       MYSQL_DB_HOST: mysql:3306
       MYSQL_USER: "${MYSQL_USER}"
       MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
       MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
    - dbdata:/var/lib/mysql
    networks:
      - app-network

  php:
    depends_on:
    - mysql
    build:
      context: .
      dockerfile: phpdockerfile
    container_name: php
    restart: unless-stopped
    env_file: .env
    environment:
       WORDPRESS_DB_HOST: mysql:3306
       WORDPRESS_DB_USER: "${MYSQL_USER}"
       WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
       WORDPRESS_DB_NAME: wordpress
    ports:
    - 9000:9000
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:1.15.12-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge